version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name install dependency
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: test frontend
          command: |
            cd xbook-frontend
            sudo npm install -g npm@latest
            npm install
            ls -al
      - run:
          name: test backend
          command: |
            cd xbook-backend
            pip3 install flask, unittest
            python3 test.py
