version: 2.1
jobs:
  frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test frontend
          command: |
            cd xbook-frontend
            sudo npm install -g npm@latest
            npm i @testing-library/react
            npm install
            npm test
  backend:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: test backend
          command: |
            cd xbook-backend
            export GOOGLE_APPLICATION_CREDENTIALS="./meta_files/xbook010-5d1f27feba42.json" 
            sudo pip install -r ./meta_files/requirements.txt
            (./meta_files/cloud_sql_proxy -instances=xbook010:us-west1:xbook-db=tcp:3307) & (sleep 10; python test.py)

workflows:
  version: 2.1
  build:
    jobs:
      - frontend
      - backend
