version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test frontend
          command: |
            cd xbook-frontend
            sudo npm install -g npm@latest
            npm install
            ls -al
      - run:
          name: test backend
          command: |
            cd xbook-backend
            pip install flask, unittest
            python3 test.py
