version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: CD to frontend
          command: |
            cd xbook-frontend
            ls -al
      - run:
          name: CD to backend
          command: |
            cd xbook-backend
            ls -al
