version: 2.1
jobs:
  one:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test frontend
          command: |
            cd xbook-frontend
            sudo npm install -g npm@latest
            npm install
            npm test
  two:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: test backend
          command: |
            cd xbook-backend
            sudo pip install -r requirements.txt
            sudo pip install flask-cors --upgrade
            python test.py

workflows:
  version: 2.1
  build:
    jobs:
      - one
      - two
